name: My First Action
on: push
jobs:
  deploy:
    name: react_on_push:
    runs-on: ubuntu-latest
    steps:
    - name: discord
      uses: sebastianpopp/discord-action@releases/v2
      with:
        webhook: $ {{ secrets.SECRET_NINJA }}
        message: $ {{ github.repository }} has been successfullt deployed.
